// পিডিএফে সমীকরণ এবং ফন্ট একদম অবিকল রাখার ১০০% কার্যকর ফাংশন
  const handleDownloadPDF = async (messageText: string) => {
    const win = window as any;
    if (!win.html2pdf) {
      alert("পিডিএফ লাইব্রেরিটি এখনো লোড হচ্ছে। অনুগ্রহ করে কয়েক সেকেন্ড পর ট্রাই করুন।");
      return;
    }

    // ১. একটি কন্টেইনার তৈরি যা স্ক্রিনের ভেতরেই থাকবে কিন্তু দেখা যাবে না
    const container = document.createElement('div');
    container.id = 'pdf-render-node';
    Object.assign(container.style, {
      position: 'fixed',
      top: '0',
      left: '0',
      width: '800px', // A4 Scale Fix
      backgroundColor: '#ffffff',
      zIndex: '-10000',
      opacity: '1', // জিরো অপাসিটি দিলে অনেক সময় ব্ল্যাংক আসে, তাই ১ রেখে লেয়ার নিচে পাঠানো হয়েছে
      pointerEvents: 'none'
    });

    const processedText = autoWrapMathDelimiters(messageText);
    
    // ২. স্ট্রাকচারড এইচটিএমএল তৈরি
    const formattedHtml = processedText.split('\n').map((line) => {
      if (line.trim().startsWith('###')) {
        return `<h2 style="font-size: 22px; font-weight: 700; margin: 25px 0 15px 0; border-left: 5px solid #10b981; padding-left: 12px; color: #059669; font-family: 'Hind Siliguri', sans-serif;">${line.replace('###', '').trim()}</h2>`;
      }
      
      const tokens = line.split(/(\$\$.*?\$\$|\$.*?\$)/g);
      const lineHtml = tokens.map((token) => {
        if (token.startsWith('$$') && token.endsWith('$$')) {
          return win.katex ? win.katex.renderToString(token.slice(2, -2), { displayMode: true, throwOnError: false }) : token;
        }
        if (token.startsWith('$') && token.endsWith('$')) {
          return win.katex ? win.katex.renderToString(token.slice(1, -1), { displayMode: false, throwOnError: false }) : token;
        }
        return token.replace(/\*\*(.*?)\*\*/g, '<strong style="color: #059669; font-weight: 700;">$1</strong>');
      }).join('');

      return `<p style="font-size: 16px; margin-bottom: 15px; line-height: 1.8; color: #1e293b; font-family: 'Hind Siliguri', sans-serif; text-align: justify;">${lineHtml}</p>`;
    }).join('');

    container.innerHTML = `
      <div style="padding: 50px; background-color: #ffffff;">
        <div style="border-bottom: 3px solid #10b981; padding-bottom: 15px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center;">
          <div>
            <h1 style="color: #059669; margin: 0; font-size: 26px; font-weight: 700; font-family: 'Hind Siliguri', sans-serif;">${subject} — লেকচার নোট</h1>
            <p style="color: #64748b; margin: 5px 0 0 0; font-size: 13px; font-family: 'Hind Siliguri', sans-serif;">Generated by Saiyed AI Tutor</p>
          </div>
          <div style="font-size: 12px; color: #94a3b8; font-family: 'Hind Siliguri', sans-serif;">তারিখ: ${new Date().toLocaleDateString('bn-BD')}</div>
        </div>
        <div style="font-family: 'Hind Siliguri', sans-serif;">${formattedHtml}</div>
      </div>
    `;

    document.body.appendChild(container);

    // ৩. পিডিএফ জেনারেট করার আগে ইমেজ এবং ফন্ট লোডিং নিশ্চিত করা
    try {
      if (document.fonts && document.fonts.ready) {
        await document.fonts.ready;
      }

      const options = {
        margin: [10, 10, 10, 10],
        filename: `${subject}_Note_SaiyedAI.pdf`,
        image: { type: 'jpeg', quality: 1.0 },
        html2canvas: { 
          scale: 2, 
          useCORS: true, 
          logging: false,
          letterRendering: true // যুক্তাক্ষর ভাঙা রোধ করতে এটি এখন True
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
      };

      // html2pdf সরাসরি কল করার পরিবর্তে এলিমেন্টটি রেন্ডার হওয়ার জন্য সামান্য ওয়েট করা
      setTimeout(async () => {
        await win.html2pdf().from(container).set(options).save();
        document.body.removeChild(container);
      }, 500);

    } catch (error) {
      console.error("PDF Generation Error:", error);
      document.body.removeChild(container);
      alert("পিডিএফ তৈরি করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।");
    }
  };