import React, { useState, useRef, useEffect } from 'react';
import { Subject, ChatMessage, AppUser, ClassLevel, Group } from '../types';
import { getTutorResponseStream } from '../geminiService';

interface TutorProps {
  user: AppUser;
  classLevel: ClassLevel;
  group: Group;
  subject: Subject;
  history: ChatMessage[];
  onUpdateHistory: (msgs: ChatMessage[]) => void;
  onBack: () => void;
}

// ==========================================
// প্রম্পট ব্যাংক (আগের মতোই অপরিবর্তিত)
// ==========================================
const SAIYED_PROMPTS = [
  "সাঈদ সম্পর্কে বিস্তারিত জানতে চাই", "সাঈদ এআই এর নির্মাতা কে এবং এর লক্ষ্য কী?", 
  "সাঈদ এর ব্যাকএন্ডে কোন প্রযুক্তির ব্যবহার করা হয়েছে?", "সাঈদ এআই কীভাবে জটিল সমস্যার সমাধান করে?", 
  "সাঈদ এআই-এর বিশেষ ক্ষমতাগুলো কী কী?", "সাঈদ এআই কি আমাকে পরীক্ষার রুটিন বানাতে সাহায্য করতে পারবে?", 
  "সাঈদ এআই তৈরি করার পেছনে মূল অনুপ্রেরণা কী ছিল?", "সাঈদ এআই এর ডাটা সিকিউরিটি বা নিরাপত্তা ব্যবস্থা কেমন?", 
  "সাঈদ এআই কি বাংলা এবং ইংরেজি দুটোই ভালো বোঝে?", "সাঈদ এআই কে কীভাবে আরও কার্যকরভাবে ব্যবহার করা যায়?", 
  "সাঈদ এর কাছ থেকে বেস্ট আউটপুট পাওয়ার ট্রিকস কী?", "সাঈদ এআই-এর ফিউচার বা আগামীতে কী কী ফিচার আসছে?", 
  "সাঈদ এর সাথে ভয়েস চ্যাট বা কথা বলার কোনো সুযোগ আছে কি?", "সাঈদ কি কঠিন বিষয়ের নোট বা সামারি তৈরি করে দিতে পারে?"
];

const SUBJECT_PROMPTS: Record<string, string[]> = {
  "গণিত": ["গণিতের বেসিক ভয় দূর করার কিছু উপায় বলো", "বীজগণিতের সূত্রগুলো সহজে মনে রাখার ট্রিকস কী?", "জ্যামিতির উপপাদ্য মুখস্থ না করে কীভাবে বুঝবো?"],
  "ইংরেজি": ["ইংরেজি গ্রামারের টেন্স (Tense) সহজে চেনার উপায় কী?", "সহজে নতুন নতুন English Vocabulary মনে রাখার উপায় কী?"],
  "default": ["এই বিষয়ের মূল সিলেবাস এবং রোডম্যাপটি দাও", "পরীক্ষার জন্য কোন কোন অধ্যায় সবচেয়ে গুরুত্বপূর্ণ?"]
};

const Tutor: React.FC<TutorProps> = ({ user, subject, history, onUpdateHistory, onBack, classLevel, group }) => {
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0); 
  const [initialSuggestions, setInitialSuggestions] = useState<string[]>([]); 
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const shuffledSaiyed = [...SAIYED_PROMPTS].sort(() => 0.5 - Math.random()).slice(0, 2);
    const subjectPool = SUBJECT_PROMPTS[subject] || SUBJECT_PROMPTS["default"];
    const shuffledSubject = [...subjectPool].sort(() => 0.5 - Math.random()).slice(0, 2);
    const finalMixed = [...shuffledSaiyed, ...shuffledSubject].sort(() => 0.5 - Math.random());
    setInitialSuggestions(finalMixed);
  }, [subject, history.length === 0]);

  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    const win = window as any;  
    if (win.renderMathInElement) {  
      setTimeout(() => {  
        win.renderMathInElement(document.body, {  
          delimiters: [{ left: "$$", right: "$$", display: true }, { left: "$", right: "$", display: false }],
          throwOnError: false  
        });  
      }, 100);  
    }
  }, [history, loading]);

  useEffect(() => {
    let interval: any;
    if (loading) {
      setLoadingStep(0);
      interval = setInterval(() => { setLoadingStep((prev) => (prev < 4 ? prev + 1 : 0)); }, 1500); 
    }
    return () => clearInterval(interval);
  }, [loading]);

  const handleDownloadPDF = (messageText: string) => {
    const win = window as any;
    if (!win.html2pdf) {
      alert("পিডিএফ লাইব্রেরিটি লোড হচ্ছে, ১ সেকেন্ড অপেক্ষা করে আবার চেষ্টা করুন।");
      return;
    }
    const element = document.createElement('div');
    let cleanText = messageText.replace(/\*\*/g, '').replace(/###/g, ''); 
    element.innerHTML = `
      <div style="font-family: Arial, sans-serif; padding: 30px; color: #1e293b; background-color: #ffffff;">
        <div style="border-bottom: 2px solid #10b981; padding-bottom: 10px; margin-bottom: 20px;">
          <h1 style="color: #059669; margin: 0; font-size: 22px;">${subject} — লেকচার নোট</h1>
          <p style="color: #64748b; margin: 5px 0 0 0; font-size: 12px;">Generated by Saiyed AI Tutor</p>
        </div>
        <div style="font-size: 14px; line-height: 1.7; white-space: pre-wrap; color: #334155;">${cleanText}</div>
      </div>
    `;
    const options = {
      margin: 10,
      filename: `${subject}_Note.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };
    win.html2pdf().from(element).set(options).save();
  };

  const handleSend = async (text?: string) => {
    const msgText = text || input;
    if (!msgText.trim() || loading) return;
    const userMsg: ChatMessage = { role: 'user', text: msgText, timestamp: Date.now() };  
    const currentHistory = [...history, userMsg];  
    onUpdateHistory(currentHistory);  
    setInput('');  
    setLoading(true);  
    const aiPlaceholder: ChatMessage = { role: 'model', text: '', timestamp: Date.now() };  
    onUpdateHistory([...currentHistory, aiPlaceholder]);  
    try {  
      await getTutorResponseStream(msgText, { classLevel, group, subject, user }, currentHistory.map(m => ({ role: m.role, parts: [{ text: m.text }] })), (streamedText) => {  
        let cleanText = streamedText;  
        let suggestions: string[] = [];  
        const sugMatch = streamedText.match(/\[SUGGESTIONS:\s*(.*?)\]/i); 
        if (sugMatch) { cleanText = streamedText.replace(sugMatch[0], '').trim(); suggestions = sugMatch[1].split(',').map(s => s.trim()); }  
        onUpdateHistory([...currentHistory, { ...aiPlaceholder, text: cleanText, suggestions }]);  
      });  
    } catch (e) { onUpdateHistory([...currentHistory, { ...aiPlaceholder, text: "⚠️ ত্রুটি হয়েছে।" }]); } finally { setLoading(false); }
  };

  const renderText = (text: string) => {
    if (!text) return null;
    return text.replace(/\$/g, '').split('\n').map((line, i) => {  
      if (line.trim().startsWith('###')) return <h2 key={i} className="text-[22px] font-black mt-6 mb-4 border-l-4 border-emerald-500 pl-3">{line.replace('###', '').trim()}</h2>;
      const processBold = (content: string) => content.split(/\*\*(.*?)\*\*/g).map((part, pi) => pi % 2 === 1 ? <strong key={pi} className="text-emerald-600">{part}</strong> : part);
      return <p key={i} className="text-[16px] mb-3 leading-relaxed">{processBold(line)}</p>;
    });
  };

  return (
    <div className="fixed inset-0 z-[60] flex flex-col bg-white dark:bg-[#0d0d0d]">
      <header className="px-4 py-3 flex items-center justify-between border-b dark:border-white/5 bg-white/80 dark:bg-[#0d0d0d]/80 backdrop-blur-xl sticky top-0 z-50">
        <div className="flex items-center space-x-3">
          <button onClick={onBack} className="p-2 text-slate-500"><svg viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" strokeWidth="3" fill="none"><polyline points="15 18 9 12 15 6"/></svg></button>
          <h2 className="text-[15px] font-black dark:text-white">{subject}</h2>
        </div>
      </header>

      <div ref={scrollRef} className="flex-1 overflow-y-auto px-4 md:px-0 pt-6 pb-32">  
        <div className="max-w-2xl mx-auto space-y-8">  
          {history.length === 0 && (
            <div className="py-20 text-center">
              <h1 className="text-2xl font-black mb-8 dark:text-white">কি শিখতে চান?</h1>
              <div className="flex flex-col space-y-3">
                {initialSuggestions.map((s, i) => (
                  <button key={i} onClick={() => handleSend(s)} className="p-4 bg-slate-50 dark:bg-white/5 rounded-xl text-left font-bold text-[14px]">{s}</button>
                ))}
              </div>
            </div>
          )}

          {history.map((m, i) => (  
            <div key={i} className={`flex flex-col ${m.role === 'user' ? 'items-end' : 'items-start'}`}>  
              <div className={`${m.role === 'user' ? 'max-w-[90%] bg-slate-100 dark:bg-white/10 p-4 rounded-2xl' : 'w-full'}`}>  
                {m.role === 'model' && i === history.length - 1 && loading && !m.text ? (
                  <div className="flex space-x-2 p-4 text-emerald-500 animate-pulse font-black text-xs">সাঈদ এআই গভীরভাবে ভাবছে...</div>
                ) : (
                  <div className="prose dark:prose-invert max-w-none text-slate-800 dark:text-slate-200">
                    {renderText(m.text)}
                  </div>
                )}

                {/* ✅ মোবাইল এবং ডেক্সটপ ফ্রেন্ডলি PDF বাটন */}
                {m.role === 'model' && m.text && (
                  <div className="mt-4 w-full flex justify-end relative z-20">
                    <button
                      onClick={() => handleDownloadPDF(m.text)}
                      className="flex items-center space-x-2 px-3 py-2.5 bg-emerald-500 text-white text-[12px] font-black rounded-lg shadow-md active:scale-95 transition-all"
                    >
                      <svg viewBox="0 0 24 24" width="14" height="14" stroke="currentColor" strokeWidth="3" fill="none"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3"/></svg>
                      <span>PDF ডাউনলোড</span>
                    </button>
                  </div>
                )}

                {m.suggestions && m.suggestions.length > 0 && (  
                   <div className="mt-8 flex flex-wrap gap-2">  
                     {m.suggestions.map((s, si) => (  
                       <button key={si} onClick={() => handleSend(s)} className="px-4 py-2 bg-emerald-50 text-emerald-600 text-[12px] font-black rounded-full border border-emerald-100">{s}</button>  
                     ))}  
                   </div>  
                )}  
              </div>  
            </div>  
          ))}  
        </div>  
      </div>  

      <div className="p-4 bg-white dark:bg-[#0d0d0d] border-t dark:border-white/5 pb-6">  
        <div className="max-w-2xl mx-auto flex items-end bg-slate-100 dark:bg-white/5 p-2 rounded-2xl border dark:border-white/10">  
           <textarea   
             rows={1} value={input} onChange={(e) => setInput(e.target.value)}
             placeholder="প্রশ্ন করুন..."  
             className="flex-1 bg-transparent px-4 py-3 outline-none font-bold text-[16px] dark:text-white resize-none"  
           />  
           <button onClick={() => handleSend()} disabled={!input.trim() || loading} className="p-3 bg-emerald-600 text-white rounded-full"><svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor"><path d="M2.01 21L23 12 2.01 3 2 10l15 2-15 2z"/></svg></button>  
        </div>  
      </div>  
    </div>
  );
};

export default Tutor;